### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by yoonsanghyu** [NUAAerJC/classifier-free-diffusion-guidance#5]
I run the code just without editing and meet this error.
What is the problem..?

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from diffusion import GaussianDiffusion
  File "/workspace/sanghyu.yoon/nfsdata/home/sanghyu.yoon/code/research_23/classifier-free-diffusion-guidance-Pytorch/diffusion.py", line 8, in <module>
    class GaussianDiffusion(nn.Module):
  File "/workspace/sanghyu.yoon/nfsdata/home/sanghyu.yoon/code/research_23/classifier-free-diffusion-guidance-Pytorch/diffusion.py", line 79, in GaussianDiffusion
    def q_mean_variance(self, x_0:torch.Tensor, t:torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
TypeError: 'type' object is not subscriptable

**Comment by jcwang-gh** [comment]
It seems that you are using an earlier version of Python 3.9. If you do not want to upgrade your Python, you can change the annotation to use `typing.Tuple` instead of `tuple`. Here are the changes you should take:
```python
from typing import Tuple

# def q_mean_variance(self, x_0:torch.Tensor, t:torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
def q_mean_variance(self, x_0:torch.Tensor, t:torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
```
Hope this helps.

**Comment by yoonsanghyu** [comment]
Thank you.....so......much...!!!!! It works well!
